Repository ui5-community/bestofui5-data, pull requests merged in 2022-08, with the labels that each got.

#71 added 3 more packages
  sources.json
Labels: new package

#72 fix: do not crash if no license at github repo
  src/gh-repos.ts
Labels: bug

#73 Added generator for UI5 Library using TypeScript
  sources.json
Labels: new package

#76 feat: add changelog to package object
  src/Package.ts
  src/gh-repos.ts
  src/types.d.ts
Labels: enhancement

#77 feat: add new package ui5-tooling-transpile
  sources.json
Labels: new package

#78 feat: add new ui5 app generator
  sources.json
Labels: new package
